gui:
  skipDiscardChangeConfirm: false

  # Use nerd fonts for better icons
  nerdFontsVersion: "3"

  # Use delta for syntax-highlighting in diff views
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  showFileTree: true # Matches the 'nvim-tree' or 'neo-tree' feel
  sidePanelWidth: 0.3 # Gives more room to the diff preview
